[project]
name = "parse-fel-data"
version = "0.3.0"
description = "Small CLI to parse FEL data and generate master-display string"
license = "MIT"
readme = "README.md"
authors = [{ name = "jlw_4049", email = "jessielw4049@gmail.com" }]
requires-python = ">=3.11,<3.14"
dependencies = ["pymediainfo>=7.0.1"]

[project.optional-dependencies]
build = ["pyinstaller-hooks-contrib>=2025.1", "pyinstaller>=6.9.0"]

[tool.ruff]
line-length = 88

[tool.basedpyright]
include = ["parse_fel_data.py"]
typeCheckingMode = "standard"
